edition = "2018"
max_width = 80

normalize_comments = true
wrap_comments = true

merge_imports = true
normalize_doc_attributes = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
