[package]
name = "aurpc"
version = "0.1.0"
authors = ["Eduardo Leegwater Simões <eduardols@protonmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.6.1"
futures = "0.3.5"

[dev-dependencies]
async-std = { version = "1.6.1", features = ["attributes"] }
